apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: r2fb34l2z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/r2fb34l2z-java-quarkus-gitops